spring:
  application:
    name: musinsa_assignment
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  # Redis 캐시 설정
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000         # 연결 타임아웃 (밀리초)
      connect-timeout: 1000 # 연결 생성 타임아웃 (밀리초)
      client-name: musinsa-cache
      lettuce:
        pool:
          max-active: 16    # 최대 연결 수
          max-idle: 8       # 최대 유휴 연결 수
          min-idle: 4       # 최소 유휴 연결 수
          max-wait: 500     # 최대 대기 시간 (밀리초)
          time-between-eviction-runs: 10000  # 유휴 연결 검사 간격 (밀리초)
  cache:
    type: redis
    redis:
      time-to-live: 60      # 캐시 항목 기본 유효시간 (초)
      cache-null-values: false
